service: astranauts-api
runtime: custom
env: flex

# Auto scaling configuration
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period: 60s
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource configuration
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Environment variables
env_variables:
  GOOGLE_CLOUD_PROJECT: astranauts-461014
  ENVIRONMENT: production

# Health check
readiness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
